### ISSUE TITLE
Create ingredient Database/Variables

### ISSUE THREAD

**Issue by MoshirMoshir** [Toaster-Eats/toaster-eats#10]
Please do work for this task in a branch named issue-10
-Create the Ingredient component containing, name, picture, description.
-Create a Note component that includes price, store, size of the ingredient it's describing. 
-Embed Note component into Ingredient component. 
-Create AddIngredient and AddNote pages that allow users, vendors to add new ingredients or add new notes on an ingredient.

**Comment by kseekins** [comment]
Coding Efforts: Ingredient, AddIngredient, Notes, AddNotes, ListNotes
Estimated Time: 4 hours, based on how much it took for comparable work on digits
