### ISSUE TITLE
Update Nav Bar with new Pages

### ISSUE THREAD

**Issue by MoshirMoshir** [Toaster-Eats/toaster-eats#25]
Please do work for this task in a branch named issue-25.

Add new pages to Nav Bar;
- Recipe Search Page
When logged in:
- Profile
-create "vendor" profile role
-diplay "Your Store's Profile" for vendors, "Your Profile" for all other roles

**Comment by kseekins** [comment]
Initially estimated 2 hours based on similar assignment on Digits. However there were 2 problems I had to figure out: how to create an additional role 'vendor' and how to change navbar items based on the roles. It had one more step of complexity than the Navbar in Digits.  I increased the estimate time to 4 hours to be safe.
