### ISSUE TITLE
Create component, collection and page for Shops

### ISSUE THREAD

**Issue by MoshirMoshir** [Toaster-Eats/toaster-eats#27]
Please do work for this task in a branch named issue-27.

Create Shop component and a page that displays all shop profiles made by those in the vendor role. 
- Shop component with required props should be made.
- Shop collection should be made
- A publication that publishes Shop collection should be made.
- A page that imports and displays the shop collection should be made.
- Create a sample data to ensure this function works.

**Comment by kseekins** [comment]
Based on the similar assignment in "Digits" I estimated 4 hours- similar to the time it took me then. I don't see foresee and issues applying the ideas in digits to this code.
