### ISSUE TITLE
Update Toaster-Eats Site

### ISSUE THREAD

**Issue by MoshirMoshir** [Toaster-Eats/toaster-eats#29]
Update the Toaster-Eats Github Page:
- **Add personal github or linkedIn links of each member to Team section**
- Update Screenshots of site
- Update description of each section if needed
- Update Link to Deployment to the https link (currently broken)

**Comment by citycoding** [comment]
- Added techfolio links for all members
- Updated landing, login, and sign up page descriptions
- Updated link to live deployment
