### ISSUE TITLE
Create Vendor Page

### ISSUE THREAD

**Issue by MoshirMoshir** [Toaster-Eats/toaster-eats#7]
Please do work for this task in a branch named issue-07
The Vendor mock up page must satisfy the following:
-Navbar items to access Recipes, Ingredients and List of Stores in the neighborhood.
-Additional Navbar item to access and edit their own store's profile. 
-Welcome message and visual items specific to Vendor Page.
-Instructions on how to use the website for vendors.

**Comment by kseekins** [comment]
Budgeting 2 hours based on my assignment to recreate professional website with meteor.
